#!/bin/bash

configs=/vagrant/flyway/conf
prodConfig=$configs/employees.properties
devConfig=$configs/employees_dev.properties
devCompareConfig=$configs/employees_dev_compare.properties

flyway_info_prod() {
  flyway/flyway info -configFile=$prodConfig
}

flyway_init_prod() {
  flyway/flyway init -configFile=$prodConfig
  flyway_info_prod
}

create_database_from_migrations() {
  if [[ -z "$@" ]]; then
    echo >&2 "You must supply the name of the database you want to create!"
    return
  fi

  database=$1
  mysqladmin drop -f $database
  mysqladmin create $database

  initDescription=New_database_marked_as_v0_so_v1_is_applied
  flyway/flyway init migrate -configFile=$configs/$database.properties -initVersion=0 -initDescription=$initDescription
}

flyway_info_dev() {
  flyway/flyway info -configFile=$devConfig
}

create_dev_database_from_migrations() {
  create_database_from_migrations employees_dev
}

create_dev_compare_database_from_migrations() {
  create_database_from_migrations employees_dev_compare
}

compare_dev_to_prod() {
  mysqldbcompare --server1=vagrant@localhost employees:employees_dev --run-all-tests --skip-data-check --skip-row-count 
}

compare_dev_to_dev_compare() {
  mysqldbcompare --server1=vagrant@localhost employees_dev:employees_dev_compare --run-all-tests --skip-data-check --skip-row-count 
}

flyway_dev() {
  flyway/flyway -configFile=$devConfig $@
}

flyway_compare() {
  flyway/flyway -configFile=$devCompareConfig $@
}

flyway_prod() {
  flyway/flyway -configFile=$prodConfig $@
}
